package libraryhome;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author User
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonAddLibrarian = new javax.swing.JButton();
        jButtonViewLibrarian = new javax.swing.JButton();
        jButtonDeleteLibrarian = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel1.setText("Add Librarian");

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel2.setText("View Librarian");

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setText("Delete Librarian");

        jButtonAddLibrarian.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jButtonAddLibrarian.setText("Add Librarian");
        jButtonAddLibrarian.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonAddLibrarianActionPerformed(evt);
            }
        });

        jButtonViewLibrarian.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jButtonViewLibrarian.setText("View Librarian");
        jButtonViewLibrarian.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonViewLibrarianActionPerformed(evt);
            }
        });

        jButtonDeleteLibrarian.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jButtonDeleteLibrarian.setText("Delete Librarian");
        jButtonDeleteLibrarian.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonDeleteLibrarianActionPerformed(evt);
            }
        });

        jButtonLogout.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddLibrarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewLibrarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteLibrarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonAddLibrarian)
                .addGap(18, 18, 18)
                .addComponent(jButtonViewLibrarian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeleteLibrarian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout)
                    .addComponent(jButtonBack))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddLibrarianActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonAddLibrarianActionPerformed
        new AddLibrarianWindow().setVisible(true);
    }//GEN-LAST:event_jButtonAddLibrarianActionPerformed

    private void jButtonViewLibrarianActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonViewLibrarianActionPerformed
        new ViewLibrarianWindow().setVisible(true);
    }//GEN-LAST:event_jButtonViewLibrarianActionPerformed

    private void jButtonDeleteLibrarianActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteLibrarianActionPerformed
        new DeleteLibrarianWindow().setVisible(true);
    }//GEN-LAST:event_jButtonDeleteLibrarianActionPerformed

    private void jButtonLogoutActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonBackActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // Replace AdminLOG with the appropriate class or remove if not needed
        // AdminLOG adminLOG = new AdminLOG();
        // adminLOG.setVisible(true);
        // this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddLibrarian;
    private javax.swing.JButton jButtonViewLibrarian;
    private javax.swing.JButton jButtonDeleteLibrarian;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}

// Additional window classes (placeholders)

class AddLibrarianWindow extends JFrame {
    public AddLibrarianWindow() {
        setTitle("Add Librarian");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JLabel label = new JLabel("Add Librarian Page");
        label.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 18));
        label.setHorizontalAlignment(JLabel.CENTER);
        add(label);
    }
}

class ViewLibrarianWindow extends JFrame {
    public ViewLibrarianWindow() {
        setTitle("View Librarian");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JLabel label = new JLabel("View Librarian Page");
        label.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 18));
        label.setHorizontalAlignment(JLabel.CENTER);
        add(label);
    }
}

class DeleteLibrarianWindow extends JFrame {
    public DeleteLibrarianWindow() {
        setTitle("Delete Librarian");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JLabel label = new JLabel("Delete Librarian Page");
        label.setFont(new Font("Yu Gothic Medium", Font.PLAIN, 18));
        label.setHorizontalAlignment(JLabel.CENTER);
        add(label);
    }
}

